### ISSUE TITLE
Error in following productions

### ISSUE THREAD

**Issue by sourabh-k** [CyberZHG/toolbox#1]
1 . A->abcdfh|abcde
2 A->abcdfh|abcde|abcdf

**Comment by CyberZHG** [comment]
![image](https://cloud.githubusercontent.com/assets/853842/22830505/ba23bb7a-efe1-11e6-9a8d-f7975105f581.png)

Note that the toy programs treat continuous characters as one token.

Are you expecting `A -> a b c d f h | a b c d e` and `A -> a b c d f h | a b c d e | a b c d f`?

https://cyberzhg.github.io/toolbox/cfg2ll?grammar=QSAtPiBhIGIgYyBkIGYgaCB8IGEgYiBjIGQgZQ==
https://cyberzhg.github.io/toolbox/lr0?grammar=QSAtPiBhIGIgYyBkIGYgaCB8IGEgYiBjIGQgZQ==
https://cyberzhg.github.io/toolbox/lr1?grammar=QSAtPiBhIGIgYyBkIGYgaCB8IGEgYiBjIGQgZQ==
https://cyberzhg.github.io/toolbox/lalr?grammar=QSAtPiBhIGIgYyBkIGYgaCB8IGEgYiBjIGQgZQ==

https://cyberzhg.github.io/toolbox/cfg2ll?grammar=QSAtPiBhIGIgYyBkIGYgaCB8IGEgYiBjIGQgZSB8IGEgYiBjIGQgZg==
https://cyberzhg.github.io/toolbox/lr0?grammar=QSAtPiBhIGIgYyBkIGYgaCB8IGEgYiBjIGQgZSB8IGEgYiBjIGQgZg==
https://cyberzhg.github.io/toolbox/lr1?grammar=QSAtPiBhIGIgYyBkIGYgaCB8IGEgYiBjIGQgZSB8IGEgYiBjIGQgZg==
https://cyberzhg.github.io/toolbox/lalr?grammar=QSAtPiBhIGIgYyBkIGYgaCB8IGEgYiBjIGQgZSB8IGEgYiBjIGQgZg==

**Comment by sourabh-k** [comment]
yeah that works fine ...
