### ISSUE TITLE
0(0+1)*1

### ISSUE THREAD

**Issue by alexhkurz** [CyberZHG/toolbox#10]
the min DFA for 0(0+1)*1 does not accept 011

it looks to me that the DFA does not take into account that it needs to continue operating in the final state 

<img width="1680" alt="Screenshot 2019-03-11 15 08 27" src="https://user-images.githubusercontent.com/42740334/54161805-9b77dc80-4410-11e9-86e0-d6169853b96b.png">

**Comment by CyberZHG** [comment]
I can't figure out why `011` should be accepted.

**Comment by alexhkurz** [comment]
0 is in the language of 0
1 is in the language of (0+1)*
1 is in the language of 1
----------------------------------
011 is in the language of 0(0+1)*1

**Comment by CyberZHG** [comment]
> The plus sign indicates __*one*__ or more occurrences of the preceding element.

**Comment by alexhkurz** [comment]
ok, I should have looked at the examples in more detail ...  I always use + for "or" ... apologies for this

looks like a very nice tool, btw ... thanks for making it available

Alexander
