### ISSUE TITLE
Result grammar is different from the original

### ISSUE THREAD

**Issue by VascoRato** [CyberZHG/toolbox#16]
I gave it the simple grammar:
```
S -> A A | B
A -> a | ϵ
B -> b
```

The resulting grammar was the following:
```
S -> A A
   | b
A -> a
B -> b
```

On the original grammar, the word `a` was valid. On the result CNF, it is not. The CNF does not define the same language as the original CFG.

**Comment by CyberZHG** [comment]
Thanks. The result now becomes:
```
S -> A A
   | ϵ
   | b
   | a
A -> a
```
