### ISSUE TITLE
Considers a null string as a terminal

### ISSUE THREAD

**Issue by adityachanekar** [CyberZHG/toolbox#18]
I was trying to find the solution to CNF of a CFG, which looked like this:
```
S -> A S B | ϵ
A -> a A S | a
B -> S b S | A | b b
```

but looking at the solution 
```
S -> H0 B
    | ϵ
 A -> H1 S
    | a
 B -> H2 S
    | H3 H3
    | H1 S
    | a
H0 -> A S
H1 -> H4 A
H2 -> S H3
H3 -> b
H4 -> a

```

It treated the epsilon as a Terminal and not a null string.

**Comment by CyberZHG** [comment]
The start symbol can contain the null string.

**Comment by adityachanekar** [comment]
Oh, thank you.
