### ISSUE TITLE
Not removing useless productions before converting to CNF

### ISSUE THREAD

**Issue by AbhinavKoul** [CyberZHG/toolbox#19]
So i tried a CFG as follows : 
```
S -> a A b | b D
A -> a
B -> b
```
Here as we can see that D is a useless production which has to be removed before we convert to CNF but the result comes as follows showing that this issue wasnt taken care of :

```
 S -> H0 B
    | B H1
 A -> a
 B -> b
H0 -> A A
H1 -> D

```

While actually the answer should have come only : 
```
 S -> H0 B
 A -> a
 B -> b
H0 -> A A

```

**Comment by CyberZHG** [comment]
That is because D is treated as a terminal.
