### ISSUE TITLE
Regular expression that contains "+"

### ISSUE THREAD

**Issue by mohammadhsn** [CyberZHG/toolbox#2]
Is there any way to handle regular expressions like `(a|b)+`? [this answer](https://cyberzhg.github.io/toolbox/nfa2dfa?regex=KGF8Yikr) seems wrong!

**Comment by EtaoinWu** [comment]
Not supported yet. Try `(a|b)(a|b)*` instead.

**Comment by CyberZHG** [comment]
Just as @EtaoinWu said, `+` is not an essential part of regex and you can always rewrite `S+` to `SS*`. However, I've added it and you can see the changes in the link you provided above. Remember to reload the script.
