### ISSUE TITLE
Supporting min DFA

### ISSUE THREAD

**Issue by murfel** [CyberZHG/toolbox#4]
Hi! The tool is really great, I absolutely love it.

That would be great to see the regex to min DFA conversion is this tool someday! For example, with Hopcroft's algorithm.

**Comment by MrOutput** [comment]
Agreed :)

**Comment by CyberZHG** [comment]
After months of procrastination, there comes the min-DFA page: https://cyberzhg.github.io/toolbox/min_dfa?regex=KGF8YikqYWJiKGF8Yikq

**Comment by MrOutput** [comment]
I just saw it! I worked out a couple minimizations manually and compared them to the generated ones; no issues :) Thanks a ton!
