### ISSUE TITLE
first and follow with url is not working!

### ISSUE THREAD

**Issue by ghost** [CyberZHG/toolbox#5]
visiting [https://cyberzhg.github.io/toolbox/first_follow?grammar=QSAtPiBBIGMgfCBBIGEgZCB8IGIgZCB8IM+1IA==](url) it doesn't show the result until i click compute

**Comment by CyberZHG** [comment]
Fixed. Thanks for opening the issue.

**Comment by ghost** [comment]
same thing goes for ll1
