### ISSUE TITLE
Min DFA seems wrong

### ISSUE THREAD

**Issue by MrOutput** [CyberZHG/toolbox#6]
Hey, Cyber, the min DFA for  there|here is producing what appears to be a min DFA for t*here. 

When I worked these manually, I ended up with 6 states:

 STATE | t | h | e | r
---|---|---|---|---
0 | 1 | 2 | - | - 
1 | - | 2 | - | - 
2 | - | - | 3 | - 
3 | - | - | - | 4 
4 | - | - | 5 | - 
5 (accepting) | - | - | - | -

**Comment by CyberZHG** [comment]
Thanks for pointing out:
https://cyberzhg.github.io/toolbox/min_dfa?regex=dGhlcmV8aGVyZQ==

**Comment by MrOutput** [comment]
Thank you :)
