### ISSUE TITLE
Request: list accepting states in tabular output

### ISSUE THREAD

**Issue by cxw42** [CyberZHG/toolbox#7]
Thank you for this tool!  I am using it for the tokenizer in cxw42/do-not-self-host#2.  Would you be willing to add a new column to the result table that shows whether or not a state is accepting?  E.g.,

|NFA STATE | DFA STATE | ACCEPTING | a | b|
|---|---|---|---|---|
|{0}|A|||B|
|{1}|B|y||

The information is currently in the state diagram, but I cannot find a place I can copy it from without manually typing it.  Thank you for considering this request!

**Comment by CyberZHG** [comment]
![image](https://user-images.githubusercontent.com/853842/48310926-18fe1e00-e5d2-11e8-87f4-7055c07d7c19.png)

**Comment by cxw42** [comment]
Wow - thanks very much for the quick response!
